name: menu_pas_mbg
description: "Aplikasi asisten dapur dan perencana gizi SPPG MBG berbasis Gemini AI."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
