name: Build APK Manual

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter Manually
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1 _flutter
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

      - name: Doctor Check
        run: flutter doctor

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
